// Code generated by tars2go 1.2.3, DO NOT EDIT.
// This file was generated from StatF.tars
// Package statf comment
package statf

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"

	"github.com/TarsCloud/TarsGo/tars/model"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
	"github.com/TarsCloud/TarsGo/tars/protocol/res/basef"
	"github.com/TarsCloud/TarsGo/tars/protocol/res/requestf"
	"github.com/TarsCloud/TarsGo/tars/protocol/tup"
	"github.com/TarsCloud/TarsGo/tars/util/current"
	"github.com/TarsCloud/TarsGo/tars/util/endpoint"
	"github.com/TarsCloud/TarsGo/tars/util/tools"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = fmt.Errorf
	_ = codec.FromInt8
	_ = bytes.ErrTooLarge
)

type StatFServant interface {
	ReportMicMsg(msg map[StatMicMsgHead]StatMicMsgBody, bFromClient bool) (ret int32, err error)
	ReportSampleMsg(msg []StatSampleMsg) (ret int32, err error)
}

type StatFServantWithContext interface {
	ReportMicMsg(tarsCtx context.Context, msg map[StatMicMsgHead]StatMicMsgBody, bFromClient bool) (ret int32, err error)
	ReportSampleMsg(tarsCtx context.Context, msg []StatSampleMsg) (ret int32, err error)
}

// StatF struct
type StatF struct {
	servant model.Servant
}

// NewStatF creates a new StatF servant.
func NewStatF() *StatF {
	return new(StatF)
}

// SetServant sets servant for the service.
func (obj *StatF) SetServant(servant model.Servant) {
	obj.servant = servant
}

// TarsSetTimeout sets the timeout for the servant which is in ms.
func (obj *StatF) TarsSetTimeout(timeout int) {
	obj.servant.TarsSetTimeout(timeout)
}

// TarsSetProtocol sets the protocol for the servant.
func (obj *StatF) TarsSetProtocol(p model.Protocol) {
	obj.servant.TarsSetProtocol(p)
}

// Endpoints returns all active endpoint.Endpoint
func (obj *StatF) Endpoints() []*endpoint.Endpoint {
	return obj.servant.Endpoints()
}

// ReportMicMsg is the proxy function for the method defined in the tars file, with the context
func (obj *StatF) ReportMicMsg(msg map[StatMicMsgHead]StatMicMsgBody, bFromClient bool, opts ...map[string]string) (int32, error) {
	return obj.ReportMicMsgWithContext(context.Background(), msg, bFromClient, opts...)
}

// ReportMicMsgWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *StatF) ReportMicMsgWithContext(tarsCtx context.Context, msg map[StatMicMsgHead]StatMicMsgBody, bFromClient bool, opts ...map[string]string) (ret int32, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteHead(codec.MAP, 1)
	if err != nil {
		return ret, err
	}
	err = buf.WriteInt32(int32(len(msg)), 0)
	if err != nil {
		return ret, err
	}
	for k0, v0 := range msg {
		err = k0.WriteBlock(buf, 0)
		if err != nil {
			return ret, err
		}
		err = v0.WriteBlock(buf, 1)
		if err != nil {
			return ret, err
		}
	}

	err = buf.WriteBool(bFromClient, 2)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "reportMicMsg", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadInt32(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// ReportMicMsgOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *StatF) ReportMicMsgOneWayWithContext(tarsCtx context.Context, msg map[StatMicMsgHead]StatMicMsgBody, bFromClient bool, opts ...map[string]string) (ret int32, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteHead(codec.MAP, 1)
	if err != nil {
		return ret, err
	}
	err = buf.WriteInt32(int32(len(msg)), 0)
	if err != nil {
		return ret, err
	}
	for k1, v1 := range msg {
		err = k1.WriteBlock(buf, 0)
		if err != nil {
			return ret, err
		}
		err = v1.WriteBlock(buf, 1)
		if err != nil {
			return ret, err
		}
	}

	err = buf.WriteBool(bFromClient, 2)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "reportMicMsg", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// ReportSampleMsg is the proxy function for the method defined in the tars file, with the context
func (obj *StatF) ReportSampleMsg(msg []StatSampleMsg, opts ...map[string]string) (int32, error) {
	return obj.ReportSampleMsgWithContext(context.Background(), msg, opts...)
}

// ReportSampleMsgWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *StatF) ReportSampleMsgWithContext(tarsCtx context.Context, msg []StatSampleMsg, opts ...map[string]string) (ret int32, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteHead(codec.LIST, 1)
	if err != nil {
		return ret, err
	}
	err = buf.WriteInt32(int32(len(msg)), 0)
	if err != nil {
		return ret, err
	}
	for _, v := range msg {
		err = v.WriteBlock(buf, 0)
		if err != nil {
			return ret, err
		}
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "reportSampleMsg", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadInt32(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// ReportSampleMsgOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *StatF) ReportSampleMsgOneWayWithContext(tarsCtx context.Context, msg []StatSampleMsg, opts ...map[string]string) (ret int32, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteHead(codec.LIST, 1)
	if err != nil {
		return ret, err
	}
	err = buf.WriteInt32(int32(len(msg)), 0)
	if err != nil {
		return ret, err
	}
	for _, v := range msg {
		err = v.WriteBlock(buf, 0)
		if err != nil {
			return ret, err
		}
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "reportSampleMsg", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// Dispatch is used to call the server side implement for the method defined in the tars file. withContext shows using context or not.
func (obj *StatF) Dispatch(tarsCtx context.Context, val interface{}, tarsReq *requestf.RequestPacket, tarsResp *requestf.ResponsePacket, withContext bool) (err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	readBuf := codec.NewReader(tools.Int8ToByte(tarsReq.SBuffer))
	buf := codec.NewBuffer()
	switch tarsReq.SFuncName {
	case "reportMicMsg":
		var msg map[StatMicMsgHead]StatMicMsgBody
		msg = make(map[StatMicMsgHead]StatMicMsgBody)
		var bFromClient bool
		if tarsReq.IVersion == basef.TARSVERSION {
			_, err = readBuf.SkipTo(codec.MAP, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadInt32(&length, 0, true)
			if err != nil {
				return err
			}
			msg = make(map[StatMicMsgHead]StatMicMsgBody)
			for i2, e2 := int32(0), length; i2 < e2; i2++ {
				var k2 StatMicMsgHead
				var v2 StatMicMsgBody
				err = k2.ReadBlock(readBuf, 0, true)
				if err != nil {
					return err
				}
				err = v2.ReadBlock(readBuf, 1, true)
				if err != nil {
					return err
				}
				msg[k2] = v2
			}
			err = readBuf.ReadBool(&bFromClient, 2, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("msg", &tupBuffer)
			readBuf.Reset(tupBuffer)
			_, err = readBuf.SkipTo(codec.MAP, 0, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadInt32(&length, 0, true)
			if err != nil {
				return err
			}
			msg = make(map[StatMicMsgHead]StatMicMsgBody)
			for i3, e3 := int32(0), length; i3 < e3; i3++ {
				var k3 StatMicMsgHead
				var v3 StatMicMsgBody
				err = k3.ReadBlock(readBuf, 0, true)
				if err != nil {
					return err
				}
				err = v3.ReadBlock(readBuf, 1, true)
				if err != nil {
					return err
				}
				msg[k3] = v3
			}

			reqTup.GetBuffer("bFromClient", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadBool(&bFromClient, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["msg"])
				if err = json.Unmarshal(jsonStr, &msg); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["bFromClient"])
				if err = json.Unmarshal(jsonStr, &bFromClient); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		var funRet int32
		if !withContext {
			imp := val.(StatFServant)
			funRet, err = imp.ReportMicMsg(msg, bFromClient)
		} else {
			imp := val.(StatFServantWithContext)
			funRet, err = imp.ReportMicMsg(tarsCtx, msg, bFromClient)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteInt32(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteInt32(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}
	case "reportSampleMsg":
		var msg []StatSampleMsg
		msg = make([]StatSampleMsg, 0)
		if tarsReq.IVersion == basef.TARSVERSION {
			_, ty, err = readBuf.SkipToNoCheck(1, true)
			if err != nil {
				return err
			}
			if ty == codec.LIST {
				err = readBuf.ReadInt32(&length, 0, true)
				if err != nil {
					return err
				}
				msg = make([]StatSampleMsg, length)
				for i4, e4 := int32(0), length; i4 < e4; i4++ {
					err = msg[i4].ReadBlock(readBuf, 0, true)
					if err != nil {
						return err
					}
				}
			} else if ty == codec.SimpleList {
				err = fmt.Errorf("not support SimpleList type")
				if err != nil {
					return err
				}
			} else {
				err = fmt.Errorf("require vector, but not")
				if err != nil {
					return err
				}
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("msg", &tupBuffer)
			readBuf.Reset(tupBuffer)
			_, ty, err = readBuf.SkipToNoCheck(0, true)
			if err != nil {
				return err
			}
			if ty == codec.LIST {
				err = readBuf.ReadInt32(&length, 0, true)
				if err != nil {
					return err
				}
				msg = make([]StatSampleMsg, length)
				for i5, e5 := int32(0), length; i5 < e5; i5++ {
					err = msg[i5].ReadBlock(readBuf, 0, true)
					if err != nil {
						return err
					}
				}
			} else if ty == codec.SimpleList {
				err = fmt.Errorf("not support SimpleList type")
				if err != nil {
					return err
				}
			} else {
				err = fmt.Errorf("require vector, but not")
				if err != nil {
					return err
				}
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["msg"])
				if err = json.Unmarshal(jsonStr, &msg); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		var funRet int32
		if !withContext {
			imp := val.(StatFServant)
			funRet, err = imp.ReportSampleMsg(msg)
		} else {
			imp := val.(StatFServantWithContext)
			funRet, err = imp.ReportSampleMsg(tarsCtx, msg)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteInt32(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteInt32(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

	default:
		return fmt.Errorf("func mismatch")
	}
	var statusMap map[string]string
	if status, ok := current.GetResponseStatus(tarsCtx); ok && status != nil {
		statusMap = status
	}
	var contextMap map[string]string
	if ctx, ok := current.GetResponseContext(tarsCtx); ok && ctx != nil {
		contextMap = ctx
	}
	*tarsResp = requestf.ResponsePacket{
		IVersion:     tarsReq.IVersion,
		CPacketType:  0,
		IRequestId:   tarsReq.IRequestId,
		IMessageType: 0,
		IRet:         0,
		SBuffer:      tools.ByteToInt8(buf.ToBytes()),
		Status:       statusMap,
		SResultDesc:  "",
		Context:      contextMap,
	}

	_ = readBuf
	_ = buf
	_ = length
	_ = have
	_ = ty
	return nil
}
