//
// This file war generated by FastTars2go 1.0
// Generated from PropertyF.tars
// Tencent.

package propertyf

import (
	"fmt"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

type StatPropMsgBody struct {
	VInfo []StatPropInfo `json:"vInfo"`
}

func (st *StatPropMsgBody) resetDefault() {
}

func (st *StatPropMsgBody) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.resetDefault()

	err, have, ty = _is.SkipToNoCheck(0, true)
	if err != nil {
		return err
	}

	if ty == codec.LIST {
		err = _is.Read_int32(&length, 0, true)
		if err != nil {
			return err
		}
		st.VInfo = make([]StatPropInfo, length, length)
		for i0, e0 := int32(0), length; i0 < e0; i0++ {

			err = st.VInfo[i0].ReadBlock(_is, 0, false)
			if err != nil {
				return err
			}
		}
	} else if ty == codec.SIMPLE_LIST {
		err = fmt.Errorf("type not support SIMPLE_LIST.")
		if err != nil {
			return err
		}
	} else {
		err = fmt.Errorf("require vector, but not.")
		if err != nil {
			return err
		}
	}

	_ = length
	_ = have
	_ = ty
	return nil
}

func (st *StatPropMsgBody) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.resetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require StatPropMsgBody, but not exist. tag %d", tag)
		} else {
			return nil
		}
	}

	st.ReadFrom(_is)

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

func (st *StatPropMsgBody) WriteTo(_os *codec.Buffer) error {
	var err error

	err = _os.WriteHead(codec.LIST, 0)
	if err != nil {
		return err
	}
	err = _os.Write_int32(int32(len(st.VInfo)), 0)
	if err != nil {
		return err
	}
	for _, v := range st.VInfo {

		err = v.WriteBlock(_os, 0)
		if err != nil {
			return err
		}
	}

	return nil
}

func (st *StatPropMsgBody) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	st.WriteTo(_os)

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}
