// Code generated by tars2go 1.2.3, DO NOT EDIT.
// This file was generated from NotifyF.tars
// Package notifyf comment
package notifyf

import (
	"fmt"

	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = codec.FromInt8

//go:generate stringer -type NOTIFYLEVEL -trimprefix NOTIFYLEVEL_ -output notifylevel_string.go
type NOTIFYLEVEL int32

const (
	NOTIFYLEVEL_NOTIFYNORMAL NOTIFYLEVEL = 0
	NOTIFYLEVEL_NOTIFYWARN   NOTIFYLEVEL = 1
	NOTIFYLEVEL_NOTIFYERROR  NOTIFYLEVEL = 2
)

//go:generate stringer -type ReportType -trimprefix ReportType_ -output reporttype_string.go
type ReportType int32

const (
	ReportType_REPORT ReportType = 0
	ReportType_NOTIFY ReportType = 1
)

// ReportInfo struct implement
type ReportInfo struct {
	EType      ReportType  `json:"eType" tars:"eType,tag:1,require:true"`
	SApp       string      `json:"sApp" tars:"sApp,tag:2,require:true"`
	SSet       string      `json:"sSet" tars:"sSet,tag:3,require:true"`
	SContainer string      `json:"sContainer" tars:"sContainer,tag:4,require:true"`
	SServer    string      `json:"sServer" tars:"sServer,tag:5,require:true"`
	SMessage   string      `json:"sMessage" tars:"sMessage,tag:6,require:true"`
	SThreadId  string      `json:"sThreadId" tars:"sThreadId,tag:7,require:false"`
	ELevel     NOTIFYLEVEL `json:"eLevel" tars:"eLevel,tag:8,require:false"`
	SNodeName  string      `json:"sNodeName" tars:"sNodeName,tag:9,require:false"`
}

func (st *ReportInfo) ResetDefault() {
}

// ReadFrom reads  from readBuf and put into struct.
func (st *ReportInfo) ReadFrom(readBuf *codec.Reader) error {
	var (
		err    error
		length int32
		have   bool
		ty     byte
	)
	st.ResetDefault()

	err = readBuf.ReadInt32((*int32)(&st.EType), 1, true)
	if err != nil {
		return err
	}

	err = readBuf.ReadString(&st.SApp, 2, true)
	if err != nil {
		return err
	}

	err = readBuf.ReadString(&st.SSet, 3, true)
	if err != nil {
		return err
	}

	err = readBuf.ReadString(&st.SContainer, 4, true)
	if err != nil {
		return err
	}

	err = readBuf.ReadString(&st.SServer, 5, true)
	if err != nil {
		return err
	}

	err = readBuf.ReadString(&st.SMessage, 6, true)
	if err != nil {
		return err
	}

	err = readBuf.ReadString(&st.SThreadId, 7, false)
	if err != nil {
		return err
	}

	err = readBuf.ReadInt32((*int32)(&st.ELevel), 8, false)
	if err != nil {
		return err
	}

	err = readBuf.ReadString(&st.SNodeName, 9, false)
	if err != nil {
		return err
	}

	_ = err
	_ = length
	_ = have
	_ = ty
	return nil
}

// ReadBlock reads struct from the given tag , require or optional.
func (st *ReportInfo) ReadBlock(readBuf *codec.Reader, tag byte, require bool) error {
	var (
		err  error
		have bool
	)
	st.ResetDefault()

	have, err = readBuf.SkipTo(codec.StructBegin, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require ReportInfo, but not exist. tag %d", tag)
		}
		return nil
	}

	err = st.ReadFrom(readBuf)
	if err != nil {
		return err
	}

	err = readBuf.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

// WriteTo encode struct to buffer
func (st *ReportInfo) WriteTo(buf *codec.Buffer) (err error) {
	err = buf.WriteInt32(int32(st.EType), 1)
	if err != nil {
		return err
	}

	err = buf.WriteString(st.SApp, 2)
	if err != nil {
		return err
	}

	err = buf.WriteString(st.SSet, 3)
	if err != nil {
		return err
	}

	err = buf.WriteString(st.SContainer, 4)
	if err != nil {
		return err
	}

	err = buf.WriteString(st.SServer, 5)
	if err != nil {
		return err
	}

	err = buf.WriteString(st.SMessage, 6)
	if err != nil {
		return err
	}

	if st.SThreadId != "" {
		err = buf.WriteString(st.SThreadId, 7)
		if err != nil {
			return err
		}
	}

	err = buf.WriteInt32(int32(st.ELevel), 8)
	if err != nil {
		return err
	}

	if st.SNodeName != "" {
		err = buf.WriteString(st.SNodeName, 9)
		if err != nil {
			return err
		}
	}

	return err
}

// WriteBlock encode struct
func (st *ReportInfo) WriteBlock(buf *codec.Buffer, tag byte) error {
	var err error
	err = buf.WriteHead(codec.StructBegin, tag)
	if err != nil {
		return err
	}

	err = st.WriteTo(buf)
	if err != nil {
		return err
	}

	err = buf.WriteHead(codec.StructEnd, 0)
	if err != nil {
		return err
	}
	return nil
}
