# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    branches:
      only:
        - master
        - dev

    docker:
      # specify the version
      - image: circleci/golang:1.12

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/tars-go/tars
    steps:
      # clone into github.com/tars-go/tars
      - checkout
      - run: sudo apt install rename

      # specify any bash command here prefixed with `run: `
      - run:
          name: Check source can build
          command: |
            ln -s /go/src/github.com/tars-go/tars /go/src/tars
            go build

      - run:
          name: Create DemoProject
          command: |
            mkdir -p $HOME/outside_gopath/tars-go/
            cd $HOME/outside_gopath/tars-go/
            bash +x /go/src/github.com/tars-go/tars/tools/create_tars_server.sh DemoGroup DemoProject DemoServant

      - run:
          name: Compile server and client
          command: |
            cd DemoGroup/DemoProject/
            make tar
            cd client/
            go build

