APP       := Trace
TARGET    := TarsTraceFrontServer
MFLAGS    :=
DFLAGS    :=
CONFIG    := client
STRIP_FLAG:= N
J2GO_FLAG:= 

libpath=${subst :, ,$(GOPATH)}
$(eval -include scripts/makefile.tars.gomod)
