scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
  - job_name: 'observability-example'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:18081' ]